name: Litecoin
version: 1.5
author: ChewLeKitten
main: us._donut_.litecoin.Litecoin
depend: [Vault]
softdepend: [PlayerPoints, PointsAPI, PlaceholderAPI, MVdWPlaceholderAPI]
commands:
  litecoin:
    description: Opens litecoin menu
    usage: /litecoin
permissions:
  litecoin.*:
    description: Gives access to all litecoin commands
    children:
      litecoin.main: true
      litecoin.help: true
      litecoin.value: true
      litecoin.bank: true
      litecoin.tax: true
      litecoin.mine: true
      litecoin.sell: true
      litecoin.buy: true
      litecoin.transfer: true
      litecoin.give: true
      litecoin.remove: true
      litecoin.set: true
      litecoin.reload: true
      litecoin.stats: true
      litecoin.top: true
      litecoin.circulation: true
      litecoin.gui.transfer: true
      litecoin.gui.buy: true
      litecoin.gui.sell: true
      litecoin.gui.mine: true
      litecoin.blackmarket: true
      litecoin.blackmarket.edit: true
  litecoin.main:
    description: Allows /litecoin
    default: true
  litecoin.help:
    description: Allows /litecoin help
    default: true
  litecoin.value:
    description: Allows /litecoin value
    default: true
  litecoin.bank:
    description: Allows /litecoin bank
    default: true
  litecoin.tax:
    description: Allows /litecoin tax
    default: true
  litecoin.mine:
    description: Allows /litecoin mine
    default: true
  litecoin.sell:
    description: Allows /litecoin sell
    default: true
  litecoin.buy:
    description: Allows /litecoin buy
    default: true
  litecoin.transfer:
    description: Allows /litecoin transfer
    default: true
  litecoin.give:
    description: Allows /litecoin give
    default: op
  litecoin.remove:
    description: Allows /litecoin remove
    default: op
  litecoin.set:
    description: Allows /litecoin set
    default: op
  litecoin.reload:
    description: Allows /litecoin reload
    default: op
  litecoin.stats:
    description: Allows /litecoin stats
    default: true
  litecoin.top:
    description: Allows /litecoin top
    default: true
  litecoin.circulation:
    description: Allows /litecoin circulation
    default: true
  litecoin.gui.transfer:
    description: Allows transferring from GUI
    default: true
  litecoin.gui.buy:
    description: Allows buying from GUI
    default: true
  litecoin.gui.sell:
    description: Allows selling from GUI
    default: true
  litecoin.gui.mine:
    description: Allows mining from GUI
    default: true
  litecoin.blackmarket:
    description: Allows /litecoin blackmarket
    default: true
  litecoin.blackmarket.edit:
    description: Allows editing of black market
    default: op
